services:
  synapse:
    image: "matrixdotorg/synapse"
    environment:
      LETSENCRYPT_EMAIL: "${EMAIL}"
      LETSENCRYPT_HOST: "${HOST}"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_SERVER_NAME: "${HOST}"
      VIRTUAL_HOST: "${HOST}"
      VIRTUAL_PORT: "${PORT}"
    volumes:
      - "./data:/data"
    networks:
      - "matrix"
    depends_on:
      - "postgresql"
  postgresql:
    image: "postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - "postgres-data:/var/lib/postgresql/"
    restart: "always"
    networks:
      - "matrix"

volumes:
  postgres-data:

networks:
  matrix:
    external: true
